<?php

/**
 * Model_Auth_Role
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    StaffAdmin
 * @subpackage Models
 * @author     Andrew Coulton <andrew@edbookfest.co.uk>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Auth_Role extends AndrewC_Model_Auth_Role
{

}