<?php

/**
 * Model_Base_Auth_Role
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Users
 *
 * @package    StaffAdmin
 * @subpackage Models
 * @author     Andrew Coulton <andrew@edbookfest.co.uk>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class AndrewC_Model_Auth_Role extends KoDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('auth__role');
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Auth_User as Users', array(
             'refClass' => 'Model_Auth_Roleuser',
             'local' => 'role_id',
             'foreign' => 'user_id'));
    }

    /**
     * Returns a Role object, creating it in the database if it doesn't exist already
     * @param string $role
     * @param string $description
     * @return Model_Auth_Role
     */
    public static function factory($role_name, $description = null) {
        $role = Doctrine_Query::create()
                ->from('Model_Auth_Role')
                ->where('name = ?',$role_name)
                ->fetchOne();

        if ( ! $role) {
            $role = new Model_Auth_Role();
            $role->name = $role_name;
            $role->description = $description;
            $role->save();
        }
        return $role;
    }

}
